Repository HiP-App/HiP-Forms, pull requests merged in 2018-03, with the labels that each got.

#189 Iss hipm 911 - Rework of the main menu
  Sources/HipMobileUI.Droid/Resources/Resource.Designer.cs
  Sources/HipMobileUI.Tests/ViewModels/Pages/ExhibitDetailsViewModelTest.cs
  Sources/HipMobileUI/Helpers/ExtensionMethods.cs
  Sources/HipMobileUI/HipMobileUI.csproj
  Sources/HipMobileUI/Location/NearbyExhibitManager.cs
  Sources/HipMobileUI/Location/NearbyRouteManager.cs
  Sources/HipMobileUI/Pages/AchievementsDetailsExhibitPage.xaml.cs
  Sources/HipMobileUI/Pages/AchievementsDetailsRoutePage.xaml.cs
  Sources/HipMobileUI/Pages/CharacterSelectionPage.xaml.cs
  Sources/HipMobileUI/Pages/ExhibitDetailsPage.xaml.cs
  Sources/HipMobileUI/Pages/ExhibitPreviewPage.xaml
  Sources/HipMobileUI/Pages/ExhibitPreviewPage.xaml.cs
  Sources/HipMobileUI/Pages/MainPage.xaml
  Sources/HipMobileUI/Pages/MainPage.xaml.cs
  Sources/HipMobileUI/Pages/RoutePreviewPage.xaml
  Sources/HipMobileUI/Pages/RoutePreviewPage.xaml.cs
  Sources/HipMobileUI/Resources/Strings.Designer.cs
  Sources/HipMobileUI/Resources/Strings.de.resx
  Sources/HipMobileUI/Resources/Strings.resx
  Sources/HipMobileUI/ViewModels/Pages/AchievementsDetailsExhibitPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/AchievementsDetailsRoutePageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/AppetizerPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/ExhibitDetailsPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/ExhibitPreviewPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/MainPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/RoutePreviewPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Views/AchievementViewModel.cs
  Sources/HipMobileUI/ViewModels/Views/DummyViewModel.cs
Labels: feature

#197 Condnl. visibility on score
  Sources/HipMobileUI/Views/AchievementsScreenView.xaml
Labels: bug

#199 Small changes for a more consistent UI experience
  Sources/HipMobileUI/App.xaml
  Sources/HipMobileUI/Pages/AppetizerPage.xaml
  Sources/HipMobileUI/Pages/ExhibitRouteDownloadPage.xaml
  Sources/HipMobileUI/Pages/UserRatingPage.xaml
  Sources/HipMobileUI/Views/LicenseScreenView.xaml
  Sources/HipMobileUI/Views/ProfileScreenView.xaml
  Sources/HipMobileUI/Views/RoutesOverviewView.xaml
Labels: minor changes

#200 Iss hipm 929 ratingtoappetizer
  Sources/HipMobileUI/Pages/UserRatingPage.xaml.cs
  Sources/HipMobileUI/ViewModels/Pages/ExhibitDetailsPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/UserRatingPageViewModel.cs
Labels: improvement

#201 HIPM-920: Add debug login button
  Sources/HipMobileUI.Droid/Resources/Resource.Designer.cs
  Sources/HipMobileUI/Resources/Strings.Designer.cs
  Sources/HipMobileUI/Resources/Strings.de.resx
  Sources/HipMobileUI/Resources/Strings.resx
  Sources/HipMobileUI/ViewModels/Views/LoginScreenViewModel.cs
  Sources/HipMobileUI/Views/LoginScreenView.xaml
  Sources/HipMobileUI/Views/LoginScreenView.xaml.cs
Labels: enhancement, minor changes

#206 Conditionally show additional information button
  Sources/HipMobileUI/Controls/HideableToolbarItem.cs
  Sources/HipMobileUI/HipMobileUI.csproj
  Sources/HipMobileUI/Pages/ExhibitDetailsPage.xaml
  Sources/HipMobileUI/Pages/ExhibitDetailsPage.xaml.cs
  Sources/HipMobileUI/ViewModels/Pages/ExhibitDetailsPageViewModel.cs
Labels: enhancement

#208 Iss hipm 924 - Status bar now always visible
  Sources/HipMobileUI.Droid/Contracts/DroidStatusBarController.cs
  Sources/HipMobileUI.Droid/HipMobileUI.Droid.csproj
  Sources/HipMobileUI.Droid/MainActivity.cs
  Sources/HipMobileUI.Tests/ViewModels/Pages/UserOnboardingItemViewModelTest.cs
  Sources/HipMobileUI.Tests/ViewModels/Pages/UserOnboardingPageViewModelTest.cs
  Sources/HipMobileUI.iOS/AppDelegate.cs
  Sources/HipMobileUI.iOS/Contracts/IosStatusBarController.cs
  Sources/HipMobileUI.iOS/HipMobileUI.iOS.csproj
  Sources/HipMobileUI/Contracts/IStatusBarController.cs
  Sources/HipMobileUI/HipMobileUI.csproj
  Sources/HipMobileUI/Navigation/NavigationService.cs
  Sources/HipMobileUI/Pages/UserOnboardingPage.xaml.cs
  Sources/HipMobileUI/ViewModels/Pages/CharacterDetailsPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/LoadingPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/MainPageViewModel.cs
  Sources/HipMobileUI/Views/ExhibitsOverviewView.xaml.cs
Labels: bug, minor changes

#205 Use actual exhibit description as text on AppetizerPage
  Sources/HipMobileUI/ViewModels/Pages/AppetizerPageViewModel.cs
Labels: bug, minor changes

#202 Iss hipm 925 - Unify the preview pages for exhibits and routes in one generic preview page
  Sources/HipMobileUI/Location/NearbyExhibitManager.cs
  Sources/HipMobileUI/Location/NearbyRouteManager.cs
  Sources/HipMobileUI/Pages/ExhibitPreviewPage.xaml
  Sources/HipMobileUI/Pages/ExhibitPreviewPage.xaml.cs
  Sources/HipMobileUI/Pages/ExhibitRoutePreviewPage.xaml
  Sources/HipMobileUI/Pages/ExhibitRoutePreviewPage.xaml.cs
  Sources/HipMobileUI/Pages/RoutePreviewPage.xaml
  Sources/HipMobileUI/Pages/RoutePreviewPage.xaml.cs
  Sources/HipMobileUI/Resources/Strings.Designer.cs
  Sources/HipMobileUI/Resources/Strings.de.resx
  Sources/HipMobileUI/Resources/Strings.resx
  Sources/HipMobileUI/ViewModels/Pages/ExhibitPreviewPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/ExhibitRoutePreviewPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/RouteDetailsPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Pages/RoutePreviewPageViewModel.cs
  Sources/HipMobileUI/ViewModels/Views/RoutesOverviewListItemViewModel.cs
  Tools/RealmWeaver.Fody.dll
Labels: improvement

#211 Fixed crash when opening license screen
  Sources/HipMobileUI/Views/LicenseScreenView.xaml
Labels: bug
